apiVersion: apps/v1
kind: Deployment
metadata:
    name: book-catalog-webapi
spec:
    replicas: 2
    selector:
        matchLabels:
            app: book-catalog-webapi
    template:
        metadata:
            labels:
                app: book-catalog-webapi
        spec:
            containers:
                - name: book-catalog-webapi
                  image: book-catalog-webapi:latest
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 8080
                  env:
                      - name: ASPNETCORE_ENVIRONMENT
                        value: Development
                      - name: ConnectionStrings__DefaultConnection
                        valueFrom:
                            secretKeyRef:
                                name: bookcatalog-secret
                                key: ConnectionStrings__DefaultConnection
